---
# Ansible playbook for a GitLab server.
#
# @todo - Install postfix `yum -y install postfix`.
#
# @author Jeff Geerling (2014).

- hosts: zaborona
  gather_facts: yes
  become: yes

  vars_files:
    - vars/openvpn.yml

  roles:
    - openvpn
