---

- name: Install OpenVPN
  include: install.yml

- name: Configure OpenVPN
  include: configure.yml

- name: Get variables №1
  include_vars: vars/zaborona1.yml

- name: Create config №1
  include: create_config.yml
  
- name: Get variables №2
  include_vars: vars/zaborona2.yml

- name: Create config №2
  include: create_config.yml
  
- name: Ensure OpenVPN is started
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
   - openvpn@zaborona1
   - openvpn@zaborona2
